title: Ashton Gomes
email: ashton.gomes@outlook.com
description: Mechanical Engineering Senior 
baseurl: "" 
url: "" 

# Build settings
markdown: kramdown
theme: jekyll-theme-primer # Keep this line to prevent build errors, though we override it
plugins:
  - jekyll-seo-tag