title: Ashton Gomes
email: ashton.gomes@outlook.com
description: Mechanical Engineering Senior
tagline: "Vehicle Dynamics Lead for Stony Brook Motorsports. Specializing in mechanical design with an interest in testing and kinematic systems."
resume_url: "/assets/Ashton_Gomes_Resume.pdf" # PDF in 'assets' folder
baseurl: "" 
url: "" 

# Build settings
markdown: kramdown
theme: jekyll-theme-primer 
plugins:
  - jekyll-seo-tag